GET http://localhost:3001/api/product
###
GET http://localhost:3001/api/product/65984afd707b54accd4585bd
###
POST http://localhost:3001/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "Product11",
    "priceInEuro" : 50,
    "description" : "product1 desc",
    "format" : "Kilograms",
    "harvest" : "1995-07-09",
    "quantity" : 1
}
###
PUT http://localhost:3001/api/product/65984b12707b54accd4585c5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "Product13",
    "priceInEuro" : 50,
    "description" : "product4 desc",
    "format" : "Kilograms",
    "harvest" : "1995-07-09",
    "quantity" : 1
}
###
DELETE http://localhost:3001/api/product/65984afd707b54accd4585bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

###

GET http://localhost:3001/api/individualClient
###
GET http://localhost:3001/api/individualClient/6598507fe141a628d64c8236
###
POST http://localhost:3001/api/individualClient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "Client",
    "surname" : "Pepe",
    "address" : "Calle del desencanto 1",
    "phoneNumber" : "123456789",
    "NIF" : "NIF1235"
}
###
PUT http://localhost:3001/api/individualClient/6598507fe141a628d64c8236
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "ClientEdit",
    "surname" : "Pepe",
    "address" : "Calle del desencanto 1",
    "phoneNumber" : "123456789",
    "NIF" : "NIF1236"
}
###
DELETE http://localhost:3001/api/product/6598507fe141a628d64c8236
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

###

GET http://localhost:3001/api/business
###
GET http://localhost:3001/api/business/65993671f5eae2c005791f10
###
POST http://localhost:3001/api/business
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "Business1",
    "address" : "Calle del desencanto 55",
    "phoneNumber" : "123456789",
    "NIF" : "NIF125",
    "CIF" : "CIF1235",
    "shippingAddress" : "address 11",
    "volumeDiscount" : 20
}
###
PUT http://localhost:3001/api/business/65993671f5eae2c005791f10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "name" : "Business1",
    "address" : "Calle del desencanto 56",
    "phoneNumber" : "123456789",
    "NIF" : "NIF1252",
    "CIF" : "CIF1238",
    "shippingAddress" : "address 11",
    "volumeDiscount" : 20
}
###
DELETE http://localhost:3001/api/business/65993671f5eae2c005791f10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

###

GET http://localhost:3001/api/productOrder
###
GET http://localhost:3001/api/productOrder/6599421a5bcf6b2828de450f
###
POST http://localhost:3001/api/productOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "idClient" : "1345",
    "basket" : {
        "Product3" : 1,
        "Product4" : 2
    },
    "status" : "finished",
    "discount" : 10
}
###
PUT http://localhost:3001/api/productOrder/6599421a5bcf6b2828de450f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw

{
    "idClient" : "65985072e141a628d64c8230",
    "basket" : {
        "Product3" : 1,
        "Product4" : 2
    },
    "status" : "finished",
    "discount" : 10,
    "totalPrice" : 70
}
###
DELETE http://localhost:3001/api/productOrder/6599421a5bcf6b2828de450f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMyYWY0NmVmNjhkOWU4YTUyYWUzMyIsImFkbWluIjoxLCJpYXQiOjE3MDIwNDc0MDMsImV4cCI6MTczMzU4MzQwM30.MEZZOq4UcyZFuRjga_kazb3jZx1oGwzi5TJVFrDwpMw
